# Generated by Django 6.0.1 on 2026-01-20 12:54

import app_repository.utils.repo_file_path
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='场景名称')),
                ('requirements', models.TextField(blank=True, help_text='如：耐高温等', verbose_name='场景技术要求')),
            ],
            options={
                'verbose_name': '应用场景',
                'verbose_name_plural': '应用场景库',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True, verbose_name='公司全称')),
                ('short_name', models.CharField(blank=True, max_length=20, verbose_name='简称')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('contact_name', models.CharField(blank=True, max_length=50, verbose_name='商务联系人')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('tech_contact', models.CharField(blank=True, max_length=50, verbose_name='技术/质量对接人')),
                ('tech_phone', models.CharField(blank=True, max_length=20, verbose_name='技术联系电话')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户库',
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='类型名称')),
                ('classification', models.CharField(choices=[('COMMODITY', '通用塑料 (PP, PE, PVC...)'), ('ENGINEERING', '工程塑料 (PA, PC, POM...)'), ('SPECIAL', '特种工程塑料 (PEEK, LCP, PPS...)'), ('FLUORINE', '氟塑料 (PTFE, PVDF...)'), ('ELASTOMER', '热塑性弹性体 (TPE, TPU...)'), ('BIO', '生物降解塑料 (PLA, PBAT...)'), ('ALLOY', '塑料合金 (PC/ABS...)'), ('OTHER', '其他')], default='ENGINEERING', max_length=20, verbose_name='塑料归类')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '材料类型',
                'verbose_name_plural': '材料类型库',
            },
        ),
        migrations.CreateModel(
            name='MetricCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序权重')),
            ],
            options={
                'verbose_name': '指标分类',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='主机厂名称')),
                ('short_name', models.CharField(blank=True, max_length=20, verbose_name='简称')),
                ('description', models.TextField(blank=True, verbose_name='描述/备注')),
            ],
            options={
                'verbose_name': '主机厂',
                'verbose_name_plural': '主机厂库',
            },
        ),
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '业务员',
                'verbose_name_plural': '业务员库',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=100, unique=True, verbose_name='材料牌号')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='生产厂家')),
                ('flammability', models.CharField(blank=True, choices=[('HB', 'HB'), ('V-2', 'V-2'), ('V-0', 'V-0'), ('5VB', '5VB'), ('5VA', '5VA')], max_length=20, verbose_name='阻燃等级')),
                ('description', models.TextField(blank=True, verbose_name='特性描述')),
                ('file_tds', models.FileField(blank=True, null=True, upload_to=app_repository.utils.repo_file_path.repo_file_path, verbose_name='TDS')),
                ('file_msds', models.FileField(blank=True, null=True, upload_to=app_repository.utils.repo_file_path.repo_file_path, verbose_name='MSDS')),
                ('file_rohs', models.FileField(blank=True, null=True, upload_to=app_repository.utils.repo_file_path.repo_file_path, verbose_name='RoHS')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('scenarios', models.ManyToManyField(blank=True, related_name='materials', to='app_repository.applicationscenario', verbose_name='适用场景')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_repository.materialtype', verbose_name='所属类型')),
            ],
            options={
                'verbose_name': '材料库',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=app_repository.utils.repo_file_path.repo_file_path)),
                ('file_type', models.CharField(choices=[('UL', 'UL黄卡/认证'), ('REACH', 'REACH报告'), ('COC', 'COC/出厂报告'), ('SPEC', '详细规格书'), ('OTHER', '其他资料')], default='OTHER', max_length=20)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_files', to='app_repository.materiallibrary')),
            ],
            options={
                'verbose_name': '材料附件',
                'verbose_name_plural': '材料附件库',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100, verbose_name='客户产品名称')),
                ('product_code', models.CharField(blank=True, max_length=100, verbose_name='产品代码/零件号')),
                ('competitor_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='竞品售价 (RMB/kg)')),
                ('target_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='目标成本 (RMB/kg)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_repository.customer', verbose_name='直接客户 (Tier1)')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_repository.materiallibrary', verbose_name='选用材料')),
                ('oem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_repository.oem', verbose_name='终端主机厂 (OEM)')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repository', to='app_project.project', verbose_name='关联项目')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_repository.salesperson', verbose_name='项目业务员')),
            ],
            options={
                'verbose_name': '项目档案',
                'verbose_name_plural': '项目档案',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=app_repository.utils.repo_file_path.repo_file_path, verbose_name='文件附件')),
                ('file_type', models.CharField(choices=[('DRAWING_2D', '2D图纸'), ('DRAWING_3D', '3D数模'), ('STANDARD', '技术标准'), ('REPORT', '检测/测试报告'), ('QUOTE', '报价/商务'), ('OTHER', '其他资料')], default='OTHER', max_length=20, verbose_name='文件类型')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='文件说明')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app_repository.projectrepository', verbose_name='所属档案')),
            ],
            options={
                'verbose_name': '项目文件',
                'verbose_name_plural': '项目文件库',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如: 拉伸强度', max_length=100, verbose_name='指标名称')),
                ('standard', models.CharField(help_text='如: ISO 527', max_length=50, verbose_name='测试标准')),
                ('condition', models.CharField(blank=True, help_text='如: 50mm/min', max_length=50, verbose_name='测试条件')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='单位')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序权重')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_repository.metriccategory', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '测试配置项',
                'ordering': ['category__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MaterialDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='测试数值')),
                ('remark', models.CharField(blank=True, max_length=50, verbose_name='备注')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='app_repository.materiallibrary')),
                ('test_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_repository.testconfig', verbose_name='测试项目')),
            ],
            options={
                'verbose_name': '性能数据',
                'ordering': ['test_config__category__order', 'test_config__order'],
            },
        ),
        migrations.AddIndex(
            model_name='materiallibrary',
            index=models.Index(fields=['-created_at'], name='app_reposit_created_3c9dc6_idx'),
        ),
        migrations.AddIndex(
            model_name='materiallibrary',
            index=models.Index(fields=['category'], name='app_reposit_categor_050e20_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfile',
            index=models.Index(fields=['-uploaded_at'], name='app_reposit_uploade_ad399d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfile',
            index=models.Index(fields=['repository'], name='app_reposit_reposit_996c0f_idx'),
        ),
        migrations.AddIndex(
            model_name='projectrepository',
            index=models.Index(fields=['-updated_at'], name='app_reposit_updated_a517fa_idx'),
        ),
        migrations.AddIndex(
            model_name='projectrepository',
            index=models.Index(fields=['project'], name='app_reposit_project_990a95_idx'),
        ),
        migrations.AddIndex(
            model_name='projectrepository',
            index=models.Index(fields=['customer'], name='app_reposit_custome_324657_idx'),
        ),
        migrations.AddIndex(
            model_name='projectrepository',
            index=models.Index(fields=['oem'], name='app_reposit_oem_id_ff1980_idx'),
        ),
        migrations.AddIndex(
            model_name='projectrepository',
            index=models.Index(fields=['salesperson'], name='app_reposit_salespe_60fbba_idx'),
        ),
        migrations.AddIndex(
            model_name='projectrepository',
            index=models.Index(fields=['material'], name='app_reposit_materia_94023e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='materialdatapoint',
            unique_together={('material', 'test_config')},
        ),
    ]
