# Generated by Django 6.0.1 on 2026-01-15 08:53

import app_repository.utils.repo_file_path
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_project', '0002_alter_projectnode_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='场景名称')),
                ('requirements', models.TextField(blank=True, help_text='如：耐高温、阻燃V0等', verbose_name='场景技术要求')),
            ],
            options={
                'verbose_name': '应用场景',
                'verbose_name_plural': '应用场景库',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True, verbose_name='公司全称')),
                ('short_name', models.CharField(blank=True, max_length=20, verbose_name='简称')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('contact_name', models.CharField(blank=True, max_length=50, verbose_name='商务联系人')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('tech_contact', models.CharField(blank=True, max_length=50, verbose_name='技术/质量对接人')),
                ('tech_phone', models.CharField(blank=True, max_length=20, verbose_name='技术联系电话')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户库',
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='类型名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '材料类型',
                'verbose_name_plural': '材料类型库',
            },
        ),
        migrations.CreateModel(
            name='MaterialLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(help_text='如: A3EG6', max_length=100, unique=True, verbose_name='材料牌号')),
                ('manufacturer', models.CharField(blank=True, help_text='如: BASF', max_length=100, verbose_name='生产厂家')),
                ('file_tds', models.FileField(blank=True, null=True, upload_to=app_repository.utils.repo_file_path.repo_file_path, verbose_name='TDS (物性表)')),
                ('file_msds', models.FileField(blank=True, null=True, upload_to=app_repository.utils.repo_file_path.repo_file_path, verbose_name='MSDS (化学品安全)')),
                ('file_rohs', models.FileField(blank=True, null=True, upload_to=app_repository.utils.repo_file_path.repo_file_path, verbose_name='RoHS/环保报告')),
                ('density', models.FloatField(blank=True, null=True, verbose_name='密度 (g/cm³)')),
                ('tensile_strength', models.FloatField(blank=True, null=True, verbose_name='拉伸强度 (MPa)')),
                ('flammability', models.CharField(blank=True, help_text='如: UL94 V0', max_length=20, verbose_name='阻燃等级')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_repository.materialtype', verbose_name='所属类型')),
            ],
            options={
                'verbose_name': '材料库',
                'verbose_name_plural': '材料库',
            },
        ),
        migrations.CreateModel(
            name='ProjectRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100, verbose_name='客户产品名称')),
                ('product_code', models.CharField(blank=True, max_length=100, verbose_name='产品代码/零件号')),
                ('file_drawing_2d', models.FileField(blank=True, null=True, upload_to=app_repository.utils.repo_file_path.repo_file_path, verbose_name='2D图纸 (PDF/DWG)')),
                ('file_drawing_3d', models.FileField(blank=True, null=True, upload_to=app_repository.utils.repo_file_path.repo_file_path, validators=[django.core.validators.FileExtensionValidator(['stp', 'step', 'prt', 'igs', 'x_t', 'zip', '7z'])], verbose_name='3D图纸 (STEP/PRT)')),
                ('file_standard', models.FileField(blank=True, null=True, upload_to=app_repository.utils.repo_file_path.repo_file_path, verbose_name='产品技术标准书')),
                ('file_inspection', models.FileField(blank=True, null=True, upload_to=app_repository.utils.repo_file_path.repo_file_path, verbose_name='专用检查/测试报告')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_repository.customer', verbose_name='所属客户')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_repository.materiallibrary', verbose_name='选用材料')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repository', to='app_project.project', verbose_name='关联项目')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_repository.applicationscenario', verbose_name='应用场景')),
            ],
            options={
                'verbose_name': '项目档案',
                'verbose_name_plural': '项目档案',
            },
        ),
    ]
