# Generated by Django 6.0.1 on 2026-01-15 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_repository', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrepository',
            name='scenario',
        ),
        migrations.AddField(
            model_name='materiallibrary',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_repository.applicationscenario', verbose_name='应用场景'),
        ),
    ]
