# Generated by Django 6.0.1 on 2026-01-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_repository', '0002_remove_projectrepository_scenario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiallibrary',
            name='ash_content',
            field=models.FloatField(blank=True, null=True, verbose_name='灰分 Ash (%)'),
        ),
        migrations.AddField(
            model_name='materiallibrary',
            name='elongation_break',
            field=models.FloatField(blank=True, null=True, verbose_name='断裂伸长率 EL (%)'),
        ),
        migrations.AddField(
            model_name='materiallibrary',
            name='flexural_modulus',
            field=models.FloatField(blank=True, null=True, verbose_name='弯曲模量 FM (MPa)'),
        ),
        migrations.AddField(
            model_name='materiallibrary',
            name='flexural_strength',
            field=models.FloatField(blank=True, null=True, verbose_name='弯曲强度 FS (MPa)'),
        ),
        migrations.AddField(
            model_name='materiallibrary',
            name='hdt_045',
            field=models.FloatField(blank=True, null=True, verbose_name='热变形温度 0.45MPa (℃)'),
        ),
        migrations.AddField(
            model_name='materiallibrary',
            name='hdt_180',
            field=models.FloatField(blank=True, null=True, verbose_name='热变形温度 1.8MPa (℃)'),
        ),
        migrations.AddField(
            model_name='materiallibrary',
            name='izod_impact_23',
            field=models.FloatField(blank=True, null=True, verbose_name='Izod缺口冲击 23℃ (kJ/m²)'),
        ),
        migrations.AddField(
            model_name='materiallibrary',
            name='izod_impact_minus_30',
            field=models.FloatField(blank=True, null=True, verbose_name='Izod缺口冲击 -30℃ (kJ/m²)'),
        ),
        migrations.AddField(
            model_name='materiallibrary',
            name='melt_index',
            field=models.FloatField(blank=True, help_text='测试标准通常为 ASTM D1238', null=True, verbose_name='熔融指数 M.I (g/10min)'),
        ),
        migrations.AddField(
            model_name='materiallibrary',
            name='shrinkage_md',
            field=models.FloatField(blank=True, null=True, verbose_name='收缩率-MD (横向 %)'),
        ),
        migrations.AddField(
            model_name='materiallibrary',
            name='shrinkage_td',
            field=models.FloatField(blank=True, null=True, verbose_name='收缩率-TD (纵向 %)'),
        ),
        migrations.AlterField(
            model_name='materiallibrary',
            name='flammability',
            field=models.CharField(blank=True, choices=[('HB', 'HB'), ('V-2', 'V-2'), ('V-1', 'V-1'), ('V-0', 'V-0'), ('5VB', '5VB'), ('5VA', '5VA')], max_length=10, null=True, verbose_name='阻燃等级'),
        ),
    ]
