# Generated by Django 6.0.1 on 2026-01-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_repository', '0003_materiallibrary_ash_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiallibrary',
            name='description',
            field=models.TextField(blank=True, help_text='例如：高流动性、抗UV、玻纤增强等特性说明', verbose_name='材料特性描述'),
        ),
        migrations.AlterField(
            model_name='applicationscenario',
            name='requirements',
            field=models.TextField(blank=True, help_text='如：耐高温等', verbose_name='场景技术要求'),
        ),
    ]
