# Generated by Django 6.0.1 on 2026-01-15 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_repository', '0004_materiallibrary_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiallibrary',
            options={'ordering': ['-created_at'], 'verbose_name': '材料库', 'verbose_name_plural': '材料库'},
        ),
        migrations.AddField(
            model_name='materiallibrary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 15, 21, 56, 26, 965184), verbose_name='录入时间'),
            preserve_default=False,
        ),
    ]
