# Generated by Django 6.0.1 on 2026-01-15 16:26

import app_repository.utils.repo_file_path
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_repository', '0005_alter_materiallibrary_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='主机厂名称')),
                ('short_name', models.CharField(blank=True, max_length=20, verbose_name='简称')),
                ('description', models.TextField(blank=True, verbose_name='描述/备注')),
            ],
            options={
                'verbose_name': '主机厂',
                'verbose_name_plural': '主机厂库',
            },
        ),
        migrations.RemoveField(
            model_name='projectrepository',
            name='file_drawing_2d',
        ),
        migrations.RemoveField(
            model_name='projectrepository',
            name='file_drawing_3d',
        ),
        migrations.RemoveField(
            model_name='projectrepository',
            name='file_inspection',
        ),
        migrations.RemoveField(
            model_name='projectrepository',
            name='file_standard',
        ),
        migrations.AddField(
            model_name='projectrepository',
            name='competitor_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='竞品售价 (RMB/kg)'),
        ),
        migrations.AddField(
            model_name='projectrepository',
            name='target_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='目标成本 (RMB/kg)'),
        ),
        migrations.AlterField(
            model_name='projectrepository',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_repository.customer', verbose_name='直接客户 (Tier1)'),
        ),
        migrations.AlterField(
            model_name='projectrepository',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新'),
        ),
        migrations.AddField(
            model_name='projectrepository',
            name='oem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_repository.oem', verbose_name='终端主机厂 (OEM)'),
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=app_repository.utils.repo_file_path.repo_file_path, verbose_name='文件附件')),
                ('file_type', models.CharField(choices=[('DRAWING_2D', '2D图纸'), ('DRAWING_3D', '3D数模'), ('STANDARD', '技术标准'), ('REPORT', '检测/测试报告'), ('QUOTE', '报价/商务'), ('OTHER', '其他资料')], default='OTHER', max_length=20, verbose_name='文件类型')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='文件说明')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app_repository.projectrepository', verbose_name='所属档案')),
            ],
            options={
                'verbose_name': '项目文件',
                'verbose_name_plural': '项目文件库',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
