# Generated by Django 6.0.1 on 2026-01-15 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_repository', '0006_oem_remove_projectrepository_file_drawing_2d_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '业务员',
                'verbose_name_plural': '业务员库',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='projectrepository',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_repository.salesperson', verbose_name='项目业务员'),
        ),
    ]
