# Generated by Django 6.0.1 on 2026-01-16 07:30

import app_repository.utils.repo_file_path
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_repository', '0007_salesperson_projectrepository_salesperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=app_repository.utils.repo_file_path.repo_file_path, verbose_name='文件附件')),
                ('file_type', models.CharField(choices=[('UL', 'UL黄卡/认证'), ('REACH', 'REACH报告'), ('COC', 'COC/出厂报告'), ('SPEC', '详细规格书'), ('OTHER', '其他资料')], default='OTHER', max_length=20, verbose_name='文件类型')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='文件说明')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_files', to='app_repository.materiallibrary', verbose_name='所属材料')),
            ],
            options={
                'verbose_name': '材料附件',
                'verbose_name_plural': '材料附件库',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
