# Generated by Django 6.0.1 on 2026-01-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_repository', '0008_materialfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiallibrary',
            name='scenario',
        ),
        migrations.AddField(
            model_name='materiallibrary',
            name='scenarios',
            field=models.ManyToManyField(blank=True, help_text='该材料可用于多个场景', related_name='materials', to='app_repository.applicationscenario', verbose_name='适用场景'),
        ),
    ]
