"""
Django settings for Django_manage project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)e+q_t^)%a1(&zrgpj=hgz6aeuj-(4edq4tgod(*s8e^(qwvcv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 允许所有ip访问
ALLOWED_HOSTS = ['*']

# 示例配置（根据你的实际访问方式修改）
CSRF_TRUSTED_ORIGINS = [
    'http://192.168.123.18:8080',  # 你的域名（http协议）
    'https://www.yourdomain.com',  # 若开启了HTTPS，必须添加对应https域名
    'http://你的服务器公网IP',  # 若用IP访问，也需添加
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres', # 用于支持PostgreSQL的高级功能
    'django_filters',  # django 列表搜索筛选器
    'django_cleanup.apps.CleanupConfig',  # 删除数据库记录时，自动删除物理文件。
    'axes', # django-axes
    'pgvector.django', # pgvector
    'app_panel.apps.AppPanelConfig',
    'app_project.apps.AppProjectConfig',
    'app_user.apps.AppUserConfig',
    'app_repository.apps.AppRepositoryConfig',
    # 【新增】配方与工艺管理
    'app_raw_material.apps.AppRawMaterialConfig',
    'app_process.apps.AppProcessConfig',
    'app_formula.apps.AppFormulaConfig',
    'app_basic_research.apps.AppBasicResearchConfig',
    'app_knowledge_base.apps.AppKnowledgeBaseConfig', # 文献知识库
    "debug_toolbar", # 这是debug_toolbar的配置
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "debug_toolbar.middleware.DebugToolbarMiddleware", # 这是debug_toolbar的配置
    'axes.middleware.AxesMiddleware', # django-axes 登录失败次数中间件
    'app_user.middleware.SecurityShieldMiddleware', # 访问盾中间件
]

ROOT_URLCONF = 'Django_manage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Django_manage.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'django_manage',
        'USER': 'admin',
        'PASSWORD': '850996480',
        'HOST': '192.168.123.47',
        'PORT': '3307',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# MEDIA_URL = 'images/'

# STATIC_ROOT是在部署的时候才发挥作用,执行 python managy.py collectstatic ，会在工程文件下生成staticfiles文件夹，把各个app下的静态文件收集到这个目录下。
# 1.在Django中setting.py文件中加入
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# 2.在终端中输入
# python manage.py collectstatic
# 3.nginx设置文件夹映射
# location /static/ {
#     alias /www/wwwroot/django_manage/staticfiles/;  # 静态文件绝对路径
#     expires 30d;  # 缓存静态文件
# }


STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),  # 记得加“,”号
)

# 【新增配置】登录/注销后的跳转地址
LOGIN_URL = 'login'  # 没登录时自动跳到这里
LOGIN_REDIRECT_URL = 'panel_home'  # 登录成功后跳到这里
LOGOUT_REDIRECT_URL = 'login'  # 注销后跳到这里

# 当用户已登录但没有所需权限时，PermissionRequiredMixin 会重定向到此 URL
PERM_DENIED_URL = '/permission-denied/'

ADMIN_URL = '/admin'

# 这是debug_toolbar的配置
INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]


# 注册页面邀请码（当注释掉邀请码时，自动关闭注册入口）
# REGISTER_INVITE_CODE = '888888'

# 自定义认证后端 (支持邮箱登录)
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend', # django-axes 认证后端
    # 'app_user.backends.EmailBackend', # 移除邮箱登录
    'django.contrib.auth.backends.ModelBackend',
]

# 邮件配置 (使用163邮箱作为示例，请替换为实际配置)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.163.com'  # SMTP服务器地址
EMAIL_PORT = 994  # SMTP端口
EMAIL_USE_SSL = True  # 使用SSL
EMAIL_HOST_USER = 'bueess@163.com'  # 发件人邮箱
EMAIL_HOST_PASSWORD = 'DXHZGGWTFIIQAHCV'  # 邮箱授权码 (非登录密码)
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # 默认发件人

# django-axes 配置
AXES_FAILURE_LIMIT = 5  # 允许失败的次数
AXES_COOLOFF_TIME = 0.0833   # 锁定时间（小时），0.0833小时约等于5分钟
AXES_RESET_ON_SUCCESS = True # 登录成功后重置失败计数
AXES_LOCKOUT_URL = '/user/login/?locked=1' # 锁定后重定向的URL (带参数)

# Session 配置
SESSION_COOKIE_AGE = 36000  # 保持登录10小时 (10 * 60 * 60)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # 默认关闭浏览器后需重新登录 (除非勾选"保持登录")