# Generated by Django 6.0.1 on 2026-01-20 12:54

import app_repository.utils.repo_file_path
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='类型名称')),
                ('code', models.CharField(blank=True, help_text='如：RESIN, FILLER', max_length=20, verbose_name='类型代码')),
                ('order', models.PositiveIntegerField(default=0, help_text='数字越小越靠前 (例如: 树脂=1, 填充=2, 助剂=3)', verbose_name='排序权重')),
            ],
            options={
                'verbose_name': '原材料类型',
                'verbose_name_plural': '原材料类型库',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='供应商名称')),
                ('sales_contact', models.CharField(blank=True, max_length=50, verbose_name='销售联系人')),
                ('sales_phone', models.CharField(blank=True, max_length=20, verbose_name='销售手机')),
                ('tech_contact', models.CharField(blank=True, max_length=50, verbose_name='技术联系人')),
                ('tech_phone', models.CharField(blank=True, max_length=20, verbose_name='技术手机')),
                ('description', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_categories', models.ManyToManyField(blank=True, related_name='suppliers', to='app_raw_material.rawmaterialtype', verbose_name='主营产品种类')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商库',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如：PA66', max_length=100, unique=True, verbose_name='原材料名称')),
                ('model_name', models.CharField(blank=True, help_text='如：2600, 101L', max_length=100, verbose_name='原材料型号')),
                ('warehouse_code', models.CharField(blank=True, help_text='ERP/WMS编码', max_length=50, null=True, unique=True, verbose_name='内部物料编码')),
                ('usage_method', models.TextField(blank=True, help_text='如：需烘干，建议添加量...', verbose_name='使用方法/描述')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='参考成本 (元/kg)')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='购入日期')),
                ('file_tds', models.FileField(blank=True, null=True, upload_to=app_repository.utils.repo_file_path.repo_file_path, verbose_name='TDS')),
                ('file_msds', models.FileField(blank=True, null=True, upload_to=app_repository.utils.repo_file_path.repo_file_path, verbose_name='MSDS')),
                ('file_rohs', models.FileField(blank=True, null=True, upload_to=app_repository.utils.repo_file_path.repo_file_path, verbose_name='RoHS')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_raw_material.rawmaterialtype', verbose_name='所属类型')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_raw_material.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '原材料',
                'verbose_name_plural': '原材料库',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterialProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='测试数值')),
                ('test_date', models.DateField(blank=True, null=True, verbose_name='测试日期')),
                ('remark', models.CharField(blank=True, max_length=50, verbose_name='备注')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='app_raw_material.rawmaterial')),
                ('test_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_repository.testconfig', verbose_name='测试项目')),
            ],
            options={
                'verbose_name': '原材料性能',
                'verbose_name_plural': '原材料性能表',
                'ordering': ['test_config__category__order', 'test_config__order'],
                'unique_together': {('raw_material', 'test_config')},
            },
        ),
    ]
