# Generated by Django 6.0.1 on 2026-01-22 06:10

import common_utils.upload_file_path
import common_utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_raw_material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='file_msds',
            field=models.FileField(blank=True, null=True, upload_to=common_utils.upload_file_path.upload_file_path, validators=[common_utils.validators.validate_file_size], verbose_name='MSDS'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='file_rohs',
            field=models.FileField(blank=True, null=True, upload_to=common_utils.upload_file_path.upload_file_path, validators=[common_utils.validators.validate_file_size], verbose_name='RoHS'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='file_tds',
            field=models.FileField(blank=True, null=True, upload_to=common_utils.upload_file_path.upload_file_path, validators=[common_utils.validators.validate_file_size], verbose_name='TDS'),
        ),
    ]
