# Generated by Django 6.0.1 on 2026-01-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_raw_material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialtype',
            name='description',
            field=models.TextField(blank=True, help_text='类型说明或备注', verbose_name='描述'),
        ),
    ]
