# Generated by Django 6.0.1 on 2026-01-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_raw_material', '0002_alter_rawmaterial_file_msds_and_more'),
        ('app_repository', '0002_alter_materialfile_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='suitable_materials',
            field=models.ManyToManyField(blank=True, related_name='raw_materials', to='app_repository.materialtype', verbose_name='适用材料体系'),
        ),
    ]
