# Generated by Django 6.0.1 on 2026-01-20 12:54

import app_repository.utils.repo_file_path
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='如：科倍隆, 南京科亚, 瑞亚', max_length=50, verbose_name='品牌')),
                ('model_name', models.CharField(help_text='如：ZSK-26, TE-35', max_length=50, unique=True, verbose_name='型号')),
                ('screw_diameter', models.FloatField(default=0, verbose_name='螺杆直径 (mm)')),
                ('ld_ratio', models.FloatField(default=40, help_text='如：40, 44, 48', verbose_name='长径比 (L/D)')),
                ('motor_power', models.FloatField(blank=True, default=0, null=True, verbose_name='电机功率 (kW)')),
                ('max_speed', models.IntegerField(blank=True, default=600, null=True, verbose_name='最高转速 (rpm)')),
                ('max_torque', models.FloatField(blank=True, default=0, null=True, verbose_name='最高扭矩 (Nm)')),
                ('description', models.TextField(blank=True, verbose_name='备注')),
                ('suitable_materials', models.ManyToManyField(blank=True, related_name='machines', to='app_repository.materialtype', verbose_name='适用材料类型')),
            ],
            options={
                'verbose_name': '机台型号',
                'verbose_name_plural': '机台型号库',
                'ordering': ['brand', 'screw_diameter'],
            },
        ),
        migrations.CreateModel(
            name='ProcessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='工艺类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('material_types', models.ManyToManyField(blank=True, related_name='process_types', to='app_repository.materialtype', verbose_name='适用材料类型')),
            ],
            options={
                'verbose_name': '工艺类型',
                'verbose_name_plural': '工艺类型库',
            },
        ),
        migrations.CreateModel(
            name='ScrewCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如：高剪切组合-V1', max_length=100, verbose_name='组合名称')),
                ('description', models.TextField(blank=True, help_text='详细描述螺杆排列逻辑，如：输送-熔融-剪切-排气', verbose_name='组合描述')),
                ('drawing_file', models.FileField(blank=True, help_text='上传螺杆排列图 (PDF/图片)', null=True, upload_to=app_repository.utils.repo_file_path.repo_file_path, verbose_name='组合图纸')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machines', models.ManyToManyField(related_name='screw_combinations', to='app_process.machinemodel', verbose_name='适用机台')),
                ('suitable_materials', models.ManyToManyField(blank=True, related_name='screw_combinations', to='app_repository.materialtype', verbose_name='适用材料类型')),
            ],
            options={
                'verbose_name': '螺杆组合',
                'verbose_name_plural': '螺杆组合库',
            },
        ),
        migrations.CreateModel(
            name='ProcessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如：PA66+30GF 标准挤出工艺', max_length=100, verbose_name='工艺方案名称')),
                ('temp_zone_1', models.IntegerField(default=0, help_text='下料口', verbose_name='一区温度 (℃)')),
                ('temp_zone_2', models.IntegerField(default=0, verbose_name='二区温度 (℃)')),
                ('temp_zone_3', models.IntegerField(default=0, verbose_name='三区温度 (℃)')),
                ('temp_zone_4', models.IntegerField(default=0, verbose_name='四区温度 (℃)')),
                ('temp_zone_5', models.IntegerField(default=0, verbose_name='五区温度 (℃)')),
                ('temp_zone_6', models.IntegerField(default=0, verbose_name='六区温度 (℃)')),
                ('temp_zone_7', models.IntegerField(default=0, verbose_name='七区温度 (℃)')),
                ('temp_zone_8', models.IntegerField(default=0, verbose_name='八区温度 (℃)')),
                ('temp_zone_9', models.IntegerField(default=0, verbose_name='九区温度 (℃)')),
                ('temp_zone_10', models.IntegerField(default=0, verbose_name='十区温度 (℃)')),
                ('temp_zone_11', models.IntegerField(default=0, verbose_name='十一区温度 (℃)')),
                ('temp_zone_12', models.IntegerField(default=0, verbose_name='十二区温度 (℃)')),
                ('temp_head', models.IntegerField(default=0, verbose_name='机头温度 (℃)')),
                ('screw_speed', models.IntegerField(default=0, verbose_name='螺杆转速 (rpm)')),
                ('torque', models.FloatField(default=0, help_text='负载百分比', verbose_name='主机扭矩 (%)')),
                ('current', models.FloatField(blank=True, default=0, null=True, verbose_name='主机电流 (A)')),
                ('melt_pressure', models.FloatField(default=0, help_text='机头压力', verbose_name='熔体压力 (MPa)')),
                ('melt_temp', models.IntegerField(default=0, help_text='手测或传感器读数', verbose_name='熔体实测温度 (℃)')),
                ('vacuum', models.FloatField(default=-0.08, verbose_name='真空度 (MPa)')),
                ('main_feeder_speed', models.FloatField(default=0, verbose_name='主喂料转速 (rpm/Hz)')),
                ('side_feeder_speed', models.FloatField(default=0, help_text='玻纤/填料', verbose_name='侧喂料转速 (rpm/Hz)')),
                ('liquid_pump_speed', models.FloatField(blank=True, default=0, null=True, verbose_name='液体泵注速度')),
                ('throughput', models.FloatField(default=0, verbose_name='总产量 (kg/h)')),
                ('cooling_method', models.CharField(choices=[('WATER_STRAND', '水冷拉条 (Water Strand)'), ('WATER_RING', '水环热切 (Water Ring)'), ('UNDERWATER', '水下切粒 (Underwater)'), ('AIR_STRAND', '风冷拉条 (Air Strand)'), ('AIR_FACE', '风冷热切 (Air Face)')], default='WATER_STRAND', max_length=20, verbose_name='切粒方式')),
                ('strand_count', models.IntegerField(default=0, help_text='机头出料孔数', verbose_name='料条根数')),
                ('water_temp', models.IntegerField(default=25, help_text='水槽温度', verbose_name='冷却水温 (℃)')),
                ('water_bath_length', models.FloatField(default=0, help_text='料条在水中的长度', verbose_name='过水长度 (m)')),
                ('air_knife_pressure', models.FloatField(blank=True, default=0, help_text='吹干风力', null=True, verbose_name='风刀压力 (MPa)')),
                ('pelletizing_speed', models.FloatField(default=0, verbose_name='切粒机转速 (rpm/Hz)')),
                ('screen_mesh', models.CharField(blank=True, help_text='如：80/100/80', max_length=50, verbose_name='过滤网目数')),
                ('qc_check_points', models.TextField(blank=True, help_text='如：每2小时检查真空口是否堵塞，每班次更换过滤网', verbose_name='QC检查/更换要点')),
                ('description', models.TextField(blank=True, verbose_name='工艺备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_process.machinemodel', verbose_name='适用机台')),
                ('process_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_process.processtype', verbose_name='工艺类型')),
                ('screw_combination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_process.screwcombination', verbose_name='螺杆组合')),
            ],
            options={
                'verbose_name': '工艺方案',
                'verbose_name_plural': '工艺方案库',
            },
        ),
    ]
