# Generated by Django 6.0.1 on 2026-01-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_process', '0001_initial'),
        ('app_repository', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processprofile',
            name='process_type',
        ),
        migrations.AddField(
            model_name='processprofile',
            name='material_types',
            field=models.ManyToManyField(blank=True, related_name='process_profiles', to='app_repository.materialtype', verbose_name='适用材料类型'),
        ),
        migrations.AddField(
            model_name='processprofile',
            name='process_type_name',
            field=models.CharField(default='双螺杆挤出', help_text='如：双螺杆挤出、注塑成型', max_length=50, verbose_name='工艺类型'),
        ),
        migrations.DeleteModel(
            name='ProcessType',
        ),
    ]
