# Generated by Django 6.0.1 on 2026-01-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_process', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screwcombination',
            options={'ordering': ['combination_code', '-created_at'], 'verbose_name': '螺杆组合', 'verbose_name_plural': '螺杆组合库'},
        ),
        migrations.AddField(
            model_name='screwcombination',
            name='combination_code',
            field=models.IntegerField(blank=True, help_text='数字编号，如：101', null=True, verbose_name='螺杆组合号'),
        ),
    ]
