# Generated by Django 6.0.1 on 2026-01-22 06:10

import common_utils.upload_file_path
import common_utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_process', '0002_alter_screwcombination_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screwcombination',
            name='drawing_file',
            field=models.FileField(blank=True, help_text='上传螺杆排列图 (PDF/图片)', null=True, upload_to=common_utils.upload_file_path.upload_file_path, validators=[common_utils.validators.validate_file_size], verbose_name='组合图纸'),
        ),
        migrations.AlterField(
            model_name='screwcombination',
            name='name',
            field=models.CharField(help_text='建议命名格式：基材+辅料 功能-版本号，如：PP+滑石粉 高剪切组合-V1', max_length=100, verbose_name='组合名称'),
        ),
    ]
