# Generated by Django 6.0.1 on 2026-01-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_process', '0002_remove_processprofile_process_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processprofile',
            name='name',
            field=models.CharField(default='PA66+30GF 标准挤出工艺 V1', help_text='如：PA66+30GF 标准挤出工艺', max_length=100, verbose_name='工艺方案名称'),
        ),
        migrations.AlterField(
            model_name='screwcombination',
            name='name',
            field=models.CharField(help_text='如：PP+滑石粉 高剪切组合-V1', max_length=100, verbose_name='组合名称'),
        ),
    ]
