# Generated by Django 6.0.1 on 2026-01-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_process', '0003_alter_processprofile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinemodel',
            name='machine_code',
            field=models.CharField(blank=True, help_text='如：1#, 2#, A-01', max_length=50, verbose_name='机台号'),
        ),
        migrations.AlterField(
            model_name='processprofile',
            name='name',
            field=models.CharField(help_text='如：PA66+30GF 标准挤出工艺', max_length=100, verbose_name='工艺方案名称'),
        ),
        migrations.AlterField(
            model_name='processprofile',
            name='screen_mesh',
            field=models.CharField(blank=True, help_text='如：80/100', max_length=50, verbose_name='过滤网目数'),
        ),
    ]
