# Generated by Django 6.0.1 on 2026-01-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_process', '0004_machinemodel_machine_code_alter_processprofile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinemodel',
            name='machine_code',
            field=models.IntegerField(blank=True, help_text='如：1, 2, 3', max_length=50, verbose_name='机台号'),
        ),
    ]
