# Generated by Django 6.0.3 on 2026-04-27 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='流程名称')),
                ('description', models.TextField(blank=True, verbose_name='流程描述')),
                ('bpmn_xml', models.TextField(verbose_name='BPMN XML 内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '流程定义',
                'verbose_name_plural': '流程定义',
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RUNNING', '运行中'), ('COMPLETED', '已完成'), ('REJECTED', '已拒绝'), ('CANCELED', '已取消')], default='RUNNING', max_length=20, verbose_name='状态')),
                ('context_data', models.JSONField(blank=True, default=dict, verbose_name='上下文数据')),
                ('spiff_workflow_data', models.JSONField(blank=True, null=True, verbose_name='Spiff状态数据')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='app_workflow.workflowdefinition', verbose_name='所属流程')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_workflows', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
            ],
            options={
                'verbose_name': '流程实例',
                'verbose_name_plural': '流程实例',
            },
        ),
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('COMPLETED', '已通过'), ('REJECTED', '已驳回'), ('CANCELED', '已取消')], default='PENDING', max_length=20, verbose_name='任务状态')),
                ('spiff_task_id', models.CharField(db_index=True, max_length=100, verbose_name='Spiff任务ID')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='审批备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_tasks', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app_workflow.workflowinstance', verbose_name='所属实例')),
            ],
            options={
                'verbose_name': '流程任务',
                'verbose_name_plural': '流程任务',
            },
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('START', '流程发起'), ('APPROVE', '审批通过'), ('REJECT', '审批驳回'), ('CANCEL', '流程取消')], max_length=20, verbose_name='操作类型')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='操作备注')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app_workflow.workflowinstance', verbose_name='所属实例')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_workflow.workflowtask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '审批历史',
                'verbose_name_plural': '审批历史',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['content_type', 'object_id'], name='app_workflo_content_2ab69f_idx'),
        ),
    ]
