# Generated by Django 6.0.3 on 2026-04-29 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstance',
            name='callback_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='回调配置'),
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='candidate_groups',
            field=models.JSONField(blank=True, default=list, verbose_name='候选组'),
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='candidate_users',
            field=models.ManyToManyField(blank=True, related_name='candidate_workflow_tasks', to=settings.AUTH_USER_MODEL, verbose_name='候选用户'),
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='spiff_instance_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Spiff任务实例ID'),
        ),
        migrations.AlterField(
            model_name='workflowtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_tasks', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='workflowtask',
            name='spiff_task_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='BPMN任务ID'),
        ),
    ]
