# Generated by Django 6.0.1 on 2026-01-20 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_process', '0001_initial'),
        ('app_raw_material', '0001_initial'),
        ('app_repository', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='自动生成，如：L20231001-01', max_length=50, unique=True, verbose_name='实验单号')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='配方名称')),
                ('cost_predicted', models.DecimalField(decimal_places=2, default=0, help_text='根据原材料成本自动计算', max_digits=10, verbose_name='BOM预测成本 (元/kg)')),
                ('cost_actual', models.DecimalField(blank=True, decimal_places=2, help_text='手动录入实际配方成本', max_digits=10, null=True, verbose_name='BOM实际成本 (元/kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='录入日期')),
                ('description', models.TextField(blank=True, verbose_name='实验目的/描述')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='实验员')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_repository.materialtype', verbose_name='基材类型')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_process.processprofile', verbose_name='生产工艺')),
                ('related_materials', models.ManyToManyField(blank=True, related_name='formulas', to='app_repository.materiallibrary', verbose_name='关联成品材料')),
            ],
            options={
                'verbose_name': '实验配方',
                'verbose_name_plural': '实验配方库',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormulaBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeding_port', models.CharField(choices=[('1_MAIN', '主喂料 (Main)'), ('2_SIDE_1', '侧喂料1 (Side 1)'), ('3_SIDE_2', '侧喂料2 (Side 2)'), ('4_LIQUID', '液体注塑 (Liquid)')], default='1_MAIN', max_length=20, verbose_name='喂料口')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='百分比/份数', max_digits=7, verbose_name='比例/份数')),
                ('is_tail', models.BooleanField(default=False, help_text='是否为上一批次的尾料回掺', verbose_name='是否尾料')),
                ('is_pre_mix', models.BooleanField(default=False, help_text='是否需要在挤出前进行预混合', verbose_name='是否共混')),
                ('pre_mix_order', models.PositiveIntegerField(default=0, help_text='数字越小越先加入', verbose_name='共混顺序')),
                ('pre_mix_time', models.PositiveIntegerField(default=0, help_text='该步骤的混合时长', verbose_name='共混时间 (秒)')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_raw_material.rawmaterial', verbose_name='原材料')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_lines', to='app_formula.labformula')),
            ],
            options={
                'verbose_name': 'BOM明细',
                'ordering': ['feeding_port', 'raw_material__category__order', 'raw_material__name'],
            },
        ),
        migrations.CreateModel(
            name='FormulaTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='测试数值')),
                ('test_date', models.DateField(blank=True, null=True, verbose_name='测试日期')),
                ('remark', models.CharField(blank=True, max_length=50, verbose_name='备注')),
                ('test_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_repository.testconfig', verbose_name='测试项目')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='app_formula.labformula')),
            ],
            options={
                'verbose_name': '实验测试结果',
                'unique_together': {('formula', 'test_config')},
            },
        ),
    ]
