# Generated by Django 6.0.1 on 2026-01-22 06:10

import common_utils.upload_file_path
import common_utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_formula', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulabom',
            options={'ordering': ['feeding_port', 'weighing_scale', 'raw_material__category__order', 'raw_material__name'], 'verbose_name': 'BOM明细'},
        ),
        migrations.AddField(
            model_name='formulabom',
            name='weighing_scale',
            field=models.CharField(choices=[('A', 'A秤 (主料)'), ('B', 'B秤 (辅料/助剂)'), ('C', 'C秤 (色粉/微量)'), ('D', 'D秤 (其他)')], default='A', help_text='用于生产投料区分', max_length=5, verbose_name='分秤'),
        ),
        migrations.AddField(
            model_name='formulatestresult',
            name='file_report',
            field=models.FileField(blank=True, null=True, upload_to=common_utils.upload_file_path.upload_file_path, validators=[common_utils.validators.validate_file_size], verbose_name='测试报告'),
        ),
    ]
