# Generated by Django 6.0.1 on 2026-01-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_formula', '0002_alter_formulabom_options_formulabom_weighing_scale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labformula',
            name='name',
            field=models.CharField(max_length=100, verbose_name='配方名称'),
        ),
    ]
