# Generated by Django 6.0.1 on 2026-01-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_formula', '0003_alter_labformula_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulabom',
            name='weighing_scale',
            field=models.CharField(choices=[('A', 'A秤 (主料1)'), ('B', 'B秤 (主料2)'), ('C', 'C秤 (辅料/助剂)'), ('D', 'D秤 (色粉/微量)'), ('E', 'E秤 (其他)')], default='A', help_text='用于生产投料区分', max_length=5, verbose_name='分秤'),
        ),
    ]
