# Generated by Django 6.0.1 on 2026-01-14 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='项目负责人')),
            ],
            options={
                'verbose_name': '项目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('INIT', '① 项目立项'), ('COLLECT', '② 收集资料'), ('FEASIBILITY', '③ 可行性评估'), ('PRICING', '④ 客户定价'), ('RND', '⑤ 研发阶段'), ('PILOT', '⑥ 客户小试'), ('MID_TEST', '⑦ 客户中试'), ('MASS_PROD', '⑧ 客户量产意向'), ('ORDER', '⑨ 客户下单情况'), ('FEEDBACK', '客户意见')], max_length=20, verbose_name='阶段')),
                ('round', models.PositiveIntegerField(default=1, verbose_name='轮次')),
                ('order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('status', models.CharField(choices=[('PENDING', '未开始'), ('DOING', '进行中'), ('DONE', '已完成'), ('FEEDBACK', '客户意见'), ('FAILED', '异常/节点迭代'), ('TERMINATED', '已终止')], default='PENDING', max_length=10, verbose_name='状态')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注/批注')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='app_project.project')),
            ],
            options={
                'verbose_name': '项目进度节点',
                'ordering': ['order'],
            },
        ),
    ]
