# Generated by Django 6.0.1 on 2026-01-13 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectnode',
            options={'ordering': ['order'], 'verbose_name': '项目进度节点'},
        ),
        migrations.AddField(
            model_name='projectnode',
            name='round',
            field=models.PositiveIntegerField(default=1, verbose_name='轮次'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='项目负责人'),
        ),
        migrations.AlterField(
            model_name='projectnode',
            name='stage',
            field=models.CharField(choices=[('INIT', '🔓项目立项'), ('COLLECT', '➕收集资料'), ('FEASIBILITY', '🧐可行性评估'), ('PRICING', '💰客户定价'), ('RND', '🧪研发阶段'), ('PILOT', '⌛️客户小试'), ('MID_TEST', '⌛️客户中试'), ('MASS_PROD', '✅量产阶段'), ('ORDER', '客户量产订单'), ('FEEDBACK', '📢客户意见/变更')], max_length=20, verbose_name='阶段'),
        ),
        migrations.AlterField(
            model_name='projectnode',
            name='status',
            field=models.CharField(choices=[('PENDING', '未开始'), ('DOING', '进行中'), ('DONE', '已完成'), ('FAILED', '不合格/需返工'), ('TERMINATED', '已终止')], default='PENDING', max_length=10, verbose_name='状态'),
        ),
    ]
