# Generated by Django 6.0.1 on 2026-01-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectnode',
            name='stage',
            field=models.CharField(choices=[('INIT', '① 项目立项'), ('COLLECT', '② 收集资料'), ('FEASIBILITY', '③ 可行性评估'), ('PRICING', '④ 客户定价'), ('RND', '⑤ 研发阶段'), ('PILOT', '⑥ 客户小试'), ('MID_TEST', '⑦ 客户中试'), ('MASS_PROD', '⑧ 客户量产意向'), ('ORDER', '⑨ 客户下单情况'), ('FEEDBACK', '🎗️客户意见')], max_length=20, verbose_name='阶段'),
        ),
    ]
